### ISSUE TITLE
Cruicial 2 Guide Book visible over backpack

### ISSUE THREAD

**Issue by kaeebonrai** [Vazkii/crucia2-issues#50]
if you equip the backpack from Quark, the crucial 2 guide book is visible over the top of its inventory slots. see screenshot
![javaw_2021-02-13_17-59-53](https://user-images.githubusercontent.com/723371/107844694-b259b180-6e25-11eb-9c8f-50b098de5a37.png)

**Comment by kaeebonrai** [comment]
tested on beta11, still bugged. 
![backpack](https://user-images.githubusercontent.com/723371/108613778-01ff3500-7445-11eb-86a5-6701358faf22.png)

**Comment by Hubry** [comment]
Vazkii, is there any specific reason why the backpack screen overrides [`init(Minecraft, int, int)`](https://github.com/Vazkii/Quark/blob/54c1504547813be5d071de73dded3b87a4ad495c/src/main/java/vazkii/quark/addons/oddities/client/screen/BackpackInventoryScreen.java#L51) instead of `init()` to move the button? Patchouli hooks the screen init post event, and that fires in the super call there.

**Comment by Vazkii** [comment]
idk

**Comment by Vazkii** [comment]
Looks fixed now in dev
